import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gsmlg_app_web, GsmlgAppWeb.Endpoint,
  url: [host: "gsmlg.app", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json"

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gsmlg_app_admin_web, GsmlgAppAdminWeb.Endpoint,
  url: [host: "admin.gsmlg.app", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Enable dev routes for dashboard and mailbox
config :gsmlg_app_admin,
  token_signing_secret: "1gdA/MEjjg9APn1rwyUsdBQ5FVA6iUIeIlUclRMFBT2i1cx3ONPx3DqxWXSDqi1w"

# Configures Swoosh API Client
config :swoosh, :api_client, GsmlgApp.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
