defmodule GsmlgAppAdmin.Repo.Migrations.AddAiTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Note: users, tokens, and posts tables already exist with required schema

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false
      add :tokens, :bigint
      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :system_prompt, :text
      add :model_params, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "conversations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :provider_id, :uuid
    end

    create table(:ai_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :provider_id,
             references(:ai_providers,
               column: :id,
               name: "conversations_provider_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create unique_index(:conversations, [:id], name: "conversations_id_index")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:messages, [:id], name: "messages_id_index")

    alter table(:ai_providers) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :api_base_url, :text, null: false
      add :api_key, :text
      add :model, :text, null: false
      add :available_models, {:array, :text}, default: []
      add :default_params, :map
      add :is_active, :boolean, null: false, default: true
      add :description, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ai_providers, [:slug], name: "ai_providers_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:ai_providers, [:slug], name: "ai_providers_unique_slug_index")

    alter table(:ai_providers) do
      remove :updated_at
      remove :created_at
      remove :description
      remove :is_active
      remove :default_params
      remove :available_models
      remove :model
      remove :api_key
      remove :api_base_url
      remove :slug
      remove :name
    end

    drop_if_exists unique_index(:messages, [:id], name: "messages_id_index")
    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id, :uuid
    end

    drop_if_exists unique_index(:conversations, [:id], name: "conversations_id_index")
    drop constraint(:conversations, "conversations_provider_id_fkey")

    alter table(:conversations) do
      modify :provider_id, :uuid
    end

    drop table(:ai_providers)
    drop constraint(:conversations, "conversations_user_id_fkey")
    drop table(:conversations)
    drop table(:messages)
  end
end
