defmodule GsmlgAppAdmin.Repo.Migrations.AddAppsTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_type, :text, null: false
      add :url, :text, null: false
      add :display_order, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :app_id, :uuid, null: false
    end

    create table(:apps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:store_links) do
      modify :app_id,
             references(:apps,
               column: :id,
               name: "store_links_app_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:apps) do
      add :name, :text, null: false
      add :label, :text, null: false
      add :short_description, :text, null: false
      add :long_description, :text
      add :icon_path, :text, null: false
      add :platforms, {:array, :text}, null: false
      add :category, :text, null: false
      add :display_order, :bigint, null: false, default: 0
      add :is_active, :boolean, null: false, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:apps, [:label], name: "apps_unique_label_index")
  end

  def down do
    drop_if_exists unique_index(:apps, [:label], name: "apps_unique_label_index")

    alter table(:apps) do
      remove :updated_at
      remove :created_at
      remove :is_active
      remove :display_order
      remove :category
      remove :platforms
      remove :icon_path
      remove :long_description
      remove :short_description
      remove :label
      remove :name
    end

    drop constraint(:store_links, "store_links_app_id_fkey")

    alter table(:store_links) do
      modify :app_id, :uuid
    end

    drop table(:apps)

    drop table(:store_links)
  end
end
